### ISSUE TITLE
Somewhat confusing authentication system

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/aptik#23]
Upon running aptik, the main window appears and then, _after_ - immediately after - that, an authentication window pops-up, asking for authentication for . . /bin/bash.

It would be better if an authentication window appeared before the main window, and for that authentication window to say, somewhere, that it is asking for permissions for _aptik_.

**Comment by teejee2008** [comment]
The GUI runs as a normal user, so it doesn't display authentication prompt before startup. After starting, it needs root access to run the **aptik** command in terminal. The "aptik" command runs as root and does the actual work of backup and restore.

Instead of prompting the user every time on clicking Backup/Restore button, it prompts once on startup.

The authentication window prompts for /bin/bash because that's what the authentication is for. The "Terminal" page in the sidebar is the rooted bash terminal that runs the aptik command.

Note: The GUI cannot run as root because it won't run on Wayland. Wayland doesn't allow GUI applications to run as root.

**Comment by CottonEaster** [comment]
What you have provided is a technical explanation for why the user must she something s/he will find odd . .

**Comment by teejee2008** [comment]
I'm explaining why this is implemented in this manner. I know that it might be confusing but I don't have a better way of implementing this. If you can think of a better way then please share your ideas.
