### ISSUE TITLE
How to exclude files with aptik-gtk ?

### ISSUE THREAD

**Issue by repsorp** [teejee2008/aptik#7]
Any file created in '/home/files/user_name'  is deleted when starting to backup
Where am I supposed to create an 'exclude.txt' file ?

**Comment by famewolf** [comment]
Is there currently no way to add files/directories to the default list of excluded entries or am I just missing it?  For example I need to skip symbolically linked folders like Downloads, Music, Ebook, etc when backing up home that point to directories on my NAS.

**Comment by teejee2008** [comment]
Symlinks are saved as symlinks while taking backup. The data it is pointing to is not included. No need to add any exclude entries.

**Comment by teejee2008** [comment]
@famewolf I don't remember if there's an option. I may have added one. Go through the code and figure it out. I have better things to do with my time.

**Comment by teejee2008** [comment]
Great. Problem solved.

**Comment by 2635599** [comment]
teejee how about actually being helpful? famewolf ask a more than fair question. aptik from what we over at mint forums has a bug. looks like when you change mount points of secondary drives and partitions on them to /home/your name/folder (partition) name instead of /home/your name/media/folder (partition) name aptik this all that data is actually on the os drive in the home folder and tries to back it up. no thanks to you over the last several day we have managed to ferret that out.

famewolf is there any chance of you sharing your script and how to use it? thanks

**Comment by teejee2008** [comment]
@2635599 This software is licensed under the [GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html) license. That means it is provided "as is" without warranty or support. You can do whatever you want with the software and the developer has zero obligations towards you. I'm not sure why you feel entitled to free support. This software may not have some features that you need (excluding folders in home for example) but that doesn't mean that I am under any obligation to implement those features.

I don't mind answering questions as long as people are being polite. But if you are going to be rude just because you feel that I didn't answer your questions properly (as in the case with famewolf above) - then you are going to have a hard time with me.

I'm locking this thread. Please do not post here again.
